### ISSUE TITLE
canvas render: dynamic text

### ISSUE THREAD

**Issue by Lyd9607** [kfitfk/kfitfk.github.io#10]
hello, I have the same question about render dynamic text with canvas render of lottie-web, what's the final measure did you use in you project? 
       And how to export all the chinese character?
       hope for you reply!

**Comment by kfitfk** [comment]
As described in this [article](https://kfitfk.github.io/programming/2019/11/24/char-outline.html), you don't export all the characters. Instead you calculate the glyph data while the user's typing.
Download the [demo](https://github.com/kfitfk/dynamic-lottie-glyph) and change the font file to a Chinese font file on your machine.
